catalog:
  rest:
    uri: http://lakekeeper:8181/catalog
    warehouse: iceberg
    s3.endpoint: http://minio:9000
    s3.region: eu-central-1
    s3.access-key-id: minioadmin
    s3.secret-access-key: minioadmin
